// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message.proto
#ifndef GRPC_message_2eproto__INCLUDED
#define GRPC_message_2eproto__INCLUDED

#include "message.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace myMessage {

class MyMessage final {
 public:
  static constexpr char const* service_full_name() {
    return "myMessage.MyMessage";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status PingPong(::grpc::ClientContext* context, const ::myMessage::Data& request, ::myMessage::Data* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::myMessage::Data>> AsyncPingPong(::grpc::ClientContext* context, const ::myMessage::Data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::myMessage::Data>>(AsyncPingPongRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::myMessage::Data>> PrepareAsyncPingPong(::grpc::ClientContext* context, const ::myMessage::Data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::myMessage::Data>>(PrepareAsyncPingPongRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void PingPong(::grpc::ClientContext* context, const ::myMessage::Data* request, ::myMessage::Data* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PingPong(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::myMessage::Data* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::myMessage::Data>* AsyncPingPongRaw(::grpc::ClientContext* context, const ::myMessage::Data& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::myMessage::Data>* PrepareAsyncPingPongRaw(::grpc::ClientContext* context, const ::myMessage::Data& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status PingPong(::grpc::ClientContext* context, const ::myMessage::Data& request, ::myMessage::Data* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::myMessage::Data>> AsyncPingPong(::grpc::ClientContext* context, const ::myMessage::Data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::myMessage::Data>>(AsyncPingPongRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::myMessage::Data>> PrepareAsyncPingPong(::grpc::ClientContext* context, const ::myMessage::Data& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::myMessage::Data>>(PrepareAsyncPingPongRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void PingPong(::grpc::ClientContext* context, const ::myMessage::Data* request, ::myMessage::Data* response, std::function<void(::grpc::Status)>) override;
      void PingPong(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::myMessage::Data* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::myMessage::Data>* AsyncPingPongRaw(::grpc::ClientContext* context, const ::myMessage::Data& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::myMessage::Data>* PrepareAsyncPingPongRaw(::grpc::ClientContext* context, const ::myMessage::Data& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PingPong_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status PingPong(::grpc::ServerContext* context, const ::myMessage::Data* request, ::myMessage::Data* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_PingPong : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_PingPong() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PingPong() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PingPong(::grpc::ServerContext* context, const ::myMessage::Data* request, ::myMessage::Data* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPingPong(::grpc::ServerContext* context, ::myMessage::Data* request, ::grpc::ServerAsyncResponseWriter< ::myMessage::Data>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PingPong<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_PingPong : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_PingPong() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::myMessage::Data, ::myMessage::Data>(
          [this](::grpc::ServerContext* context,
                 const ::myMessage::Data* request,
                 ::myMessage::Data* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->PingPong(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_PingPong() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PingPong(::grpc::ServerContext* context, const ::myMessage::Data* request, ::myMessage::Data* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void PingPong(::grpc::ServerContext* context, const ::myMessage::Data* request, ::myMessage::Data* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_PingPong<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_PingPong : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_PingPong() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PingPong() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PingPong(::grpc::ServerContext* context, const ::myMessage::Data* request, ::myMessage::Data* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_PingPong : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_PingPong() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_PingPong() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PingPong(::grpc::ServerContext* context, const ::myMessage::Data* request, ::myMessage::Data* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPingPong(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_PingPong : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_PingPong() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->PingPong(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_PingPong() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PingPong(::grpc::ServerContext* context, const ::myMessage::Data* request, ::myMessage::Data* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void PingPong(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PingPong : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_PingPong() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::myMessage::Data, ::myMessage::Data>(std::bind(&WithStreamedUnaryMethod_PingPong<BaseClass>::StreamedPingPong, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_PingPong() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PingPong(::grpc::ServerContext* context, const ::myMessage::Data* request, ::myMessage::Data* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPingPong(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::myMessage::Data,::myMessage::Data>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_PingPong<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_PingPong<Service > StreamedService;
};

}  // namespace myMessage


#endif  // GRPC_message_2eproto__INCLUDED
